### ISSUE TITLE
Questions about reproducing

### ISSUE THREAD

**Issue by longbai1006** [NeurAI-Lab/CLS-ER#1]
Hi! Thanks for the awesome work! I am trying to reproduce your results but I have some questions about the details. Thanks for your answers in advance.

1. I found that, within each task, you utilize the model of the last epoch rather than the best one. Are there any special considerations?

2. I reproduced your work on a single RTX 3090 GPU, with the default seed 1993, but I am not sure whether I chose the right value as the final accuracy. I chose the accuracy of the last task, e.g., in seq-mnist experiment, the value of task 5's accuracy, which is also the final accuracy shown in the terminal. Am I right?
![aa954fbec7ff74b2858dcc753b02cce](https://user-images.githubusercontent.com/100130932/165596867-9f63b4d4-0813-4935-a30f-34f54b476166.png)

3. Could you please let us know the exact seeds you were using? So that we might be able to get closer results.

4. We found that, during the training of most continual learning approaches, your code will have an accuracy first before starting training, as the following image. I guess it is pre-train, but I did not find the pre-trained setup. Could you please indicate how these values are obtained?
![1651084312(1)](https://user-images.githubusercontent.com/100130932/165595711-8ce5eac8-0fa6-4ad9-a9bc-d4aeb6f43b20.png)

Thank you very much again!

**Comment by fahad92virgo** [comment]
Hi, Thank you for your interest in our work. Are you trying to reproduce the results for CLS-ER? I see from the command that you are running the code for LwF. 

On the same dataset, you can run for our method using the following command:
` python main.py --dataset seq-mnist --model clser --buffer_size 500 --load_best_args`

For the mode general queries, yes task5 results show the final accuracy of the method on all the tasks trained for seq MNIST, for Rot-MNIST for instance it would be task20. 

Our method does not use a pre-trained model, in the mammoth repo, the accuracies before training are utlized to calculate the fwd transfer of the model.

Also, we do not use specific seeds in order to avoid introducing bias in evaluation, similar to DER, we run the method 10 different random seeds (this would be the case if you do not set a particular seed) and provide the average performance and standard deviation. 

 FTI, when you run for our method, you will get the evaluation results for all three models, working model, stable model and the plastic model. For inference we use the stable model, Table S1 in the appendix provides the results for all the three components for the considerd CL settings.
